server:
  shutdown: graceful
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: dew
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  redis:
    host: localhost
    port: 6379

feign:
  client:
    url: localhost:8081

